name: run-tests

on:
  push:
    branches:
      - v2
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go:
          - 1.16
          - 1.17
        clickhouse:
          - 21.8.11.4-lts
          - 21.12.3.32-stable
    steps:
      - uses: actions/checkout@v2

      - name: Add ClickHouse repo
        run: |
          sudo apt-get install apt-transport-https ca-certificates dirmngr
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4

          echo "deb https://repo.clickhouse.com/deb/stable/ main/" | sudo tee \
              /etc/apt/sources.list.d/clickhouse.list
          sudo apt-get update

      - name: Install ClickHouse ${{ matrix.clickhouse }}
        run: sudo apt-get install -y clickhouse-server=${{ matrix.clickhouse }}

      - name: Run ClickHouse
        run: sudo service clickhouse-server start

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ matrix.go }}

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"

      - name: Set up cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: clickhouse-go-${{ runner.os }}-run-tests-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            test-${{ runner.os }}-go-

      - name: Run tests
        run: go test -v ./...
